name: Build Container

on:
  push:
    paths:
      - container/build.Dockerfile
      - .github/workflows/create-build-container.yaml
  pull_request:
    paths:
      - container/build.Dockerfile
      - .github/workflows/create-build-container.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          file: container/build.Dockerfile
          tags: ghcr.io/${{ github.repository }}/terra-tracker-sensor-zephyr:latest
