name: Build Container

on:
  push:
    branches:
      - main
    paths:
      - container/build.Dockerfile
      - '.github/workflows/${{ github.workflow }}.yml'
  pull_request:
    branches:
      - main
    paths:
      - container/build.Dockerfile
      - '.github/workflows/${{ github.workflow }}.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: container/build.Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/terra-tracker-sensor-zephyr:latest
